cat "Helpers.js" > AllJavaScript.js
cat "Structures.js" >> AllJavaScript.js
cat "Game_Data.js" >> AllJavaScript.js
cat "Screen_Elements.js" >> AllJavaScript.js
cat "Status_Screen.js" >> AllJavaScript.js
cat "User_Settings.js" >> AllJavaScript.js
cat "LCD.js" >> AllJavaScript.js
cat "User_Input.js" >> AllJavaScript.js
cat "Image_Handling.js" >> AllJavaScript.js
cat "Message_Screen.js" >> AllJavaScript.js
cat "Gameplay.js" >> AllJavaScript.js
cat "Animations.js" >> AllJavaScript.js
cat "Challenges.js" >> AllJavaScript.js
cat "WiFi.js" >> AllJavaScript.js
cat "BSides.js" >> AllJavaScript.js  
cat "VirtualBadgeFunctions.js" >> AllJavaScript.js